### ISSUE TITLE
Release 3.5.1

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3529]
New point release from Blender means new point release from us. 

It's a little late, but better late than never as they say. This means, tracker is closed - then release - then new merge. Got my linux environment compiling now too. Same splashscreen in this case

Gonna work it today. 

**Tasks**
- [x] Update splashscreen + version
- [x] Create branch + release notes
- [x] Windows build
- [x] Linux Build
- [x] Linux Deb 
- [x] Linux Appimage
- [x] Mac builds
- [x] Compile documentation
- [x] Upload documentation
- [x] Do release on Github and website
- [x] Update website + release notes
- [x] Create publicity
- [x] Push

**Comment by Draise14** [comment]
I have some client work the next hour or so, then I will do this.

**Comment by ReinerBforartists** [comment]
GO GO GO

**Comment by Draise14** [comment]
Building windows and trying to build a linux one.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/236903958-dee067d6-a7a9-4ffa-9294-1ea47700da94.png)
 Compile was fine on Windows
 
![vmplayer_ckAQVN1L6M](https://user-images.githubusercontent.com/35357409/236904433-d3cccba7-519c-4d1a-bab3-2c8be03b4bb2.png)
Compiled on Ubuntu, apparently all is fine for now. 

Onwards.

**Comment by Draise14** [comment]
To do this means adding the path to the generated cmake, or generating the cmake with it right?

**Comment by Draise14** [comment]
Sean has the mac building going. I finally have my new machine compiling PDF's correctly... jeesus. 

I am so behind client work right now, and got no more time to do publicity today, will push tomorrow.

**Comment by ReinerBforartists** [comment]
Appimage is up.

I will wait with spreading the word until we have cleared if the linux version might miss Optix or not. My tared version is bigger by a few mb, which is usually the Optix lib.

**Comment by ReinerBforartists** [comment]
Manual is updated

**Comment by Draise14** [comment]
Thanks! I added in the optix path and compiled on Ubuntu with that. How can I test if it worked? I can try recompile from scratch just in case. 

The manual also auto deleted the release branch. I had a checkbox somewhere -_- I'll also release there too with the new branch today.

**Comment by ReinerBforartists** [comment]
Well, you can't without a proper graphics card. But no path means optix is skipped. With the path it compiles. And i bet your compiled and tared version is now a few mb bigger :)

**Comment by ReinerBforartists** [comment]
Mac version is up and linked.

And i have restored the Manual release branch.

**Comment by ReinerBforartists** [comment]
We still miss the updated linux tar and deb

**Comment by Draise14** [comment]
Been in crunch, just finished a 16.5 hour shift.. WIll compile those tomorrow, though theoretically optix was set before I compiled.

**Comment by ReinerBforartists** [comment]
Yes, but the path is then missing, you need to add it manually at Linux.

I'll update the files

**Comment by ReinerBforartists** [comment]
Hmmmm :D

![rebranding](https://github.com/Bforartists/Bforartists/assets/13919702/f95ff5e0-4306-408a-a187-ccd63e225e54)

**Comment by ReinerBforartists** [comment]
Either way, i'll upload mine. Here i can be sure that optix is included. And we can close this chapter.

**Comment by ReinerBforartists** [comment]
Posted the news at the usual places.

**Comment by Draise14** [comment]
Did some publicity, this is a point release so won't do a video. Nothing really new in features. So.. closing!
