### ISSUE TITLE
Release 3.6.0

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3611]
New release from Blender means new release from us. _It's coming.. probably very soon. So want to prep things._ 

Right now there still is a few shotstoppers to fix, before working this, but we do have a splashscreen!!! We hosted a competition with some donated prizes, and we had a good time with 11 entries. The best one based on a strict judgement criteria won. 

![splash](https://github.com/Bforartists/Bforartists/assets/35357409/2c4245f9-17c2-4057-98d8-27a08dc1f811)

**Tasks**
- [x] Fix Showstoppers
- [x] #3613
- [x] Update splashscreen + version
- [x] Create branch 
- [x] Create Release notes
- [x] Windows build
- [x] Linux Build
- [x] Linux Deb 
- [x] Linux Appimage
- [x] Mac builds
- [x] Compile documentation
- [x] Upload documentation
- [x] Do release on Github
- [x] Do release on website
- [x] Update release notes
- [x] Create publicity
- [x] Push

**Comment by ReinerBforartists** [comment]
At least we have a splash screen !

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f99945c8-3475-41f9-bbdc-f84fe2504e7a)

Ok.. it's out now. All hands on deck for the show stoppers.

**Comment by ReinerBforartists** [comment]
We had a merge with missing bits. So i would vote to do a full code comparison before releasing the new version.

See here: https://github.com/Bforartists/Bforartists/issues/3604

**Comment by Draise14** [comment]
I can start working on that - how do you do a full code comparison? Similar to a merge? Using Meld?

**Comment by ReinerBforartists** [comment]
Yes. But beware of Meld crashing half way through when you compare really the whole code. Better do it in chunks that the software is able to chew.

And i would wait for Iyad, or talk with Iyad since it overlaps with his showstopper issue of the file new trouble.

**Comment by Draise14** [comment]
Started doing a large meld walk through file per file, folder per folder, checking everything. It's nice seeing everything in detail, good learning experience. I will commit to a new branch to make sure I'm not breaking anything before pulling in my file check. That 3D View file though..... 

Pending: this weeks commit logs too - then will tie things up in the tracker. I have already postponed mostly everything. 

_I do have unfortunate timing of finishing up my last freelance client asap this week also, but I'll see what I can do._

**Comment by Draise14** [comment]
I've asked Iyad to make the release branch, then late Monday I'll start working the release. I'm on the road today and tomorrow.

**Comment by iyadahmed** [comment]
here
https://github.com/Bforartists/Bforartists/tree/bfa3v3.6.0
but splash screen and version numbers are not updated yet should I update them?

**Comment by Draise14** [comment]
I have those local. Damn, being on the road really sucks. 🤣

I'll commit to branch and merge to master Monday evening local.

**Comment by Draise14** [comment]
Got home 2am Monday, so doing it today, Tuesday. Compiling splash and will commit to master and branch soon.

**Comment by Draise14** [comment]
Oops, did, the wrong version bump, correcting and recompiling

**Comment by Draise14** [comment]
Github Release built
https://github.com/Bforartists/Bforartists/releases/tag/v3.6.0

**Comment by Draise14** [comment]
@ReinerBforartists I'll let you work the linux builds! I have pinged @seanr about the mac build. Once those are up, I'll push the release to the website and socials. 

Got a video in mind!

**Comment by Draise14** [comment]
Question, to get the `make update` at a certain date for a release, how do you do that?

**Comment by ReinerBforartists** [comment]
You can't. Make Update pulls the latest changes. You can switch to a specific commit afterwards though with Switch / Checkout

**Comment by ReinerBforartists** [comment]
Oh, and it says it's 3.5.1 ...

**Comment by ReinerBforartists** [comment]
Manual versioning and update history also lacks one version behind. Updating the repo and release ...

**Comment by ReinerBforartists** [comment]
Hmm, seems that we need to recreate the release for the manual. I cannot find a way to manipulate the source code attachments. 

But first the official release ...

**Comment by ReinerBforartists** [comment]
Reddit mean, doesn't let me post the news O_O

![noreddit](https://github.com/Bforartists/Bforartists/assets/13919702/71881670-80cf-4e6f-bd9f-9f8de475b41c)

**Comment by ReinerBforartists** [comment]
That's why we have two pair of eyes for :)

**Comment by Draise14** [comment]
Have started to push to socials. Reception on the Spanish facebook groups is surprisingly quite warm. I'll have to push there more often, facebook still is a social behemoth. I have yet to make some new feature publicity and the video. Still WIP.

**Comment by ReinerBforartists** [comment]
Draise mean, posts at reddit while i had it already posted :'3

I'll remove mine ^^

**Comment by ReinerBforartists** [comment]
Hm, on the other hand, my posts contains the links ^^

Let's keep it.

**Comment by Draise14** [comment]
Yeah, reddit doesn't combine images and links very well - so better multiple than one.

**Comment by Draise14** [comment]
Mac build uploaded to github and linked to github on website. I will consider this one done.
Still working on the video, but should be done soon.

**Comment by Draise14** [comment]
Will close! Let's make the next release as juicy as ever.
