### ISSUE TITLE
Release 3.6.1

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3677]
New release from Blender means we should do one too. This is an LTS release, but best to go for it here in this case, got some good bug fixes and 4.0.0 goodness in this one. 

With this build, we don't need a new splashscreen. 

**Tasks**

- [x] Update splashscreen + version
- [x] Create branch 
- [x] Create Release notes
- [x] Windows build
- [x] Linux Build
- [x] Linux Deb 
- [x] Linux Appimage
- [x] Linux Flatpak
- [x] Mac builds
- [x] Bump Version, Branch and Compile documentation
- [x] Upload documentation to Nextcloud
- [x] Do release on Github
- [x] Do release on Website
- [x] Update release notes on website
- [x] Create publicity
- [x] Push

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/bb189e7c-784e-46bd-be0e-66fa2dcb0721)

Version bumped. Committing to master.

**Comment by Draise14** [comment]
Branch made, doing a windows compile.

I am also doing an experimental ubuntu 22.04 LTS build.

**Comment by Draise14** [comment]
Documentation and windows Release done on Github, documentation on Nextcloud

**Comment by Draise14** [comment]
Ok, updated release logs. Flatpak is automating on it's way. Got a short video release ready for socials.
Got the long one over half way.

**Comment by Draise14** [comment]
I think we should push this to the website now, then add the notice to Mac. We can try get that going later hopefully...

**Comment by ReinerBforartists** [comment]
Sounds like a plan.

I have uploaded a working deb to the cloud and the release. And removed the bforartists-3.6.1-Linux.deb.txt there. The release note is linked in the description already. And bforartists-3.6.1-Linux.deb.txt is quite confusing, namewise.

**Comment by ReinerBforartists** [comment]
Appimage isn't in the cloud. Will upload there too.

**Comment by ReinerBforartists** [comment]
As a note, we should not worry about the flatpak version. The developer decided not to cooperate with us. And we are not responsible in any way for this version.

**Comment by Draise14** [comment]
Yeah, the flatpak is automated now, so it's pretty hands off. I ping the dev and all good. 660 downloads over a month, not bad. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4bdf8ee2-cfd5-4cf1-84dd-2afac4d93367)

**Comment by ReinerBforartists** [comment]
Why linked to github again? :(

The news at the page is also missing. Updating ...

**Comment by Draise14** [comment]
Ah. I can't upload to the server for those links to be server links. So I wait till you update. We've done it this way a few releases.

**Comment by Draise14** [comment]
Ah ok, ping me next time! I saw the download page on 3.6.0 still, so assumed they were not updated. 

I have a long feature release video cooking, nearly done. Then it goes to Youtube. I did a youtube short too.

**Comment by ReinerBforartists** [comment]
Will do :)

And looking forward to the video.

**Comment by Draise14** [comment]
@seanr how is the mac build? Did you manage in the end?

**Comment by ReinerBforartists** [comment]
Mac build is up, so closing this taks.
