### ISSUE TITLE
Release 3.6.2 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3709]
New point  release from Blender means we should do one too. This is an LTS release, but best to go for it here in this case, got some good bug fixes in this one. 

With this build, we don't need a new splashscreen. 

**Tasks**

- [x] Update splashscreen + version
- [x] Create branch 
- [x] Create Release notes
- [x] Windows build
- [x] Linux Build
- [x] Linux Deb 
- [x] Linux Appimage
- [ ] Mac builds
- [x] Bump Documentation Version, Branch and Compile documentation
- [x] Upload documentation to Nextcloud
- [x] Do release on Github
- [x] Do release on Website
- [x] Update release notes on website
- [x] Create publicity
- [x] Push

**Comment by Draise14** [comment]
Got a few more tasks I want to do, then will do the release branch tomorrow morning for the weekend before next merge.

**Comment by Draise14** [comment]
Created branch.

**Comment by ReinerBforartists** [comment]
Just realized that we cannot create the linux versions anymore since there is no way for me to access the cmake settings by the graphical ui and to tick with static libs. Ubuntu 22 quits then. Hmm. We could turn it on by default in the cmake settings.

**Comment by ReinerBforartists** [comment]
Let's try to modify the blender_reklease.cmake file instead as a temporary workaround.

![temporary](https://github.com/Bforartists/Bforartists/assets/13919702/d20fd55a-d074-4e90-8343-9a2613c3d5eb)

**Comment by ReinerBforartists** [comment]
Or we do it by the command line. We need to define the optix path anyways. First testing this method ...

`PATH=$PATH:/home/x/Desktop/optix/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64/include -WITH_STATIC_LIBS=ON make release`

**Comment by ReinerBforartists** [comment]
Ah, wrong order.

PATH=$PATH:/home/x/Desktop/optix/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64/include make release -WITH_STATIC_LIBS=ON

I also changed the cmake file to test things. But it remains odd.The compile result is equal big with static libs and without static libs. Makes me wonder where the static libs are.

**Comment by ReinerBforartists** [comment]
Hmm. I miss around 40 mb in the results. But i don't know where. It compiles with optix and with static libs and with Cuda. Have the Blender devs thrown out something big?

**Comment by ReinerBforartists** [comment]
That for appimage made with Ubuntu 22.04 at rocky linux 8
![rocky8](https://github.com/Bforartists/Bforartists/assets/13919702/85861109-6fdf-4f21-bc57-8bff66ed2eeb)

And Ubuntu 23 VM still doesn't let me copy n paste the files, so i cannot test it.

I guess i have finally managed not to manage it anymore.

**Comment by ReinerBforartists** [comment]
Uploaded the results to the cloud. https://cloud.bforartists.de/index.php/s/JWXadSKTHNBSm6W

I am still baffled about around 40 mb fewer size compared to version 3.6.1. But i simply cannot find the mistake.

**Comment by ReinerBforartists** [comment]
Hmm, at Ubuntu 23 the deb and tar works. But the appimage is doomed. I am just not sure if it is not my Ubuntu 23 VM, Ubuntu 23 in general, or if we really have a problem.

![doomed](https://github.com/Bforartists/Bforartists/assets/13919702/6bc2e47b-831c-4cb0-916f-8f91e140f6a7)

**Comment by ReinerBforartists** [comment]
Rocky linux moans about the wrong glibc version, like with appimage.

![glibcproblem](https://github.com/Bforartists/Bforartists/assets/13919702/cc55a151-0cc5-4ce8-aae5-7589c76ad1a1)

**Comment by ReinerBforartists** [comment]
Ah, you need to explicitely allow it to be an executable. Appimage starts \o/

Many thanks @naetherm :)

**Comment by ReinerBforartists** [comment]
Oh and we need to change the name to the BFA version number ...

**Comment by Draise14** [comment]
Oh, thought I did that one version bump, but didn't check the corner info. I see it now. I will compile the windows release tomorrow and start the moves there when I'm back at the computer.

**Comment by iyadahmed** [comment]
> Hmm. I miss around 40 mb in the results. But i don't know where. It compiles with optix and with static libs and with Cuda. Have the Blender devs thrown out something big?

HIP?

**Comment by ReinerBforartists** [comment]
Ah, good catch. HIP is off, indeed. But that's the current release settings. Then it shall stay off.

> Oh, thought I did that one version bump, but didn't check the corner info. I see it now. I will compile the windows release tomorrow and start the moves there when I'm back at the computer.

No, the release info down right is fine. It's about the file name of the appimage file. It contains the glibc version number, the x86_64 hint, but no hint what version of BFA it is. And for Ubuntu the file name is already too long. Doesn't let me rename it :D

I would vote to throw out the x86_64 hint. The very most linux desktop systems are x86. The glibc version is of interest though, and so i would want to keep it in the file name.

![ubuntucrap](https://github.com/Bforartists/Bforartists/assets/13919702/b45983ed-9224-476a-991d-e95792d46f0c)
.

**Comment by ReinerBforartists** [comment]
Either way, the Linux files are here: https://cloud.bforartists.de/index.php/s/JWXadSKTHNBSm6W

I have added the file versioning to the appimage file. We can shorten it when we have talked about the further file versioning handling of it.

**Comment by Draise14** [comment]
Ok! Will push to github now, making the windows installer! Good to be back at the computer.

**Comment by Draise14** [comment]
Github release done, website page updated with release notes, pointing to Github right now.

**Comment by Draise14** [comment]
Pushed blog post to website, making publicity.

**Comment by ReinerBforartists** [comment]
Just realized that i didn't update the manual for 3.6.1. And nobody moaned. Nobody reads the manual :D

**Comment by ReinerBforartists** [comment]
> Either way, the Linux files are here: https://cloud.bforartists.de/index.php/s/JWXadSKTHNBSm6W
> 
> I have added the file versioning to the appimage file. We can shorten it when we have talked about the further file versioning handling of it.

I have removed these files since the three linux files are in the release folder now. And our poor webspace is not unlimited ...

**Comment by Draise14** [comment]
@seanr looks like some users are keen on a mac build! Would you be down to build one?

**Comment by Draise14** [comment]
> Just realized that i didn't update the manual for 3.6.1. And nobody moaned. Nobody reads the manual :D

The manual is a huge document.. I wonder if making some quick start documentation may be better for onboarding.. I'll cook the idea.

**Comment by ReinerBforartists** [comment]
That's what the quickstart videos once were made for. But that was for version 2 ...

**Comment by ReinerBforartists** [comment]
I guess we will never see a mac version of version 3.6.2. So closing.
