### ISSUE TITLE
3D View - Create new operators to "Add Smooth by Angle Modifier"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4187]
![bforartists_zLpW0jGN8n](https://github.com/Bforartists/Bforartists/assets/35357409/6e22902a-71e6-4ef9-9916-6cb88920b69a)

Right now the modifier stack can do the "Autosmooth" UX, but adding this modifier is troublesome on a selected set of objects. You would have to add to active, then duplicate modifiers to the others, a 2 step process. Should be a one step process - and the operator should push this modifier to the bottom of the stack so it to works as a user intends it to. 

## Related tasks:

- [ ] Create operator to change angle of selection from 3D Viewport/Toolbars #4189
- [ ] Expose these operators in the Mesh Properties Editor so old users don't get lost, and can use a similar UX as if in the 3D Viewport, also make it discoverable for older users. #4190
- [ ] Create operator to push Smooth by Angle operator to bottom of stack (destructive) from 3D Viewport but as an opt-in UX (not polling always) #4192
- [x]  Create an operator that detects is autosmooth is added to the stack, and removes it. #4191
- [ ] Add "masks" toggles to autosmooth modifier to show the new power.  #4188

Here is some working code: 
1. Adds the modifier to selection
2. Moves to bottom of stack when adding

```py
import bpy

# Get all selected objects
selected_objects = bpy.context.selected_objects

for obj in selected_objects:
    # Check if the object is a mesh
    if obj.type == 'MESH':
        # Set the active object to the current object in the loop
        bpy.context.view_layer.objects.active = obj

        # Add the modifier
        bpy.ops.object.modifier_add_node_group(asset_library_type='ESSENTIALS', asset_library_identifier="", relative_asset_identifier="geometry_nodes\\smooth_by_angle.blend\\NodeTree\\Smooth by Angle")

        # Get the newly added modifier
        modifier = obj.modifiers[-1]  # The newly added modifier is at the end of the list

        # Move the modifier to the bottom of the stack
        while obj.modifiers.find(modifier.name) != len(obj.modifiers) - 1:
            bpy.ops.object.modifier_move_down(modifier=modifier.name)
```

This could be a 3D Viewport operator.

**Related UX and addon:**
Old Auto Smooth - For Blender 4.1
https://www.blendernation.com/2024/04/03/fix-auto-smooth-in-blender-4-1-with-this-free-add-ion/
https://amanbairwal.gumroad.com/l/old-auto-smooth?layout=profile&recommended_by=library

_Problem with addon is the checkbox can be iffy (checkbox breaks, unreliable) and there is no user input or feedback that it is adding a modifier and modifying the modifier. It also has a performance issue if it is polling the modifier stack to make sure the node is at the bottom of the stack at all times - which also may put autosave at risk and is destructive UX and makes the stack jitter._ 

## Task
1. Create new operator
2. Expose to Header, Toolbar and Context menu, and Toolshelf 
3. Document

**Comment by Draise14** [comment]
Blender is thinking to add this to a degree
- The add Smooth by Angle modifier will be added
- Pinning a modifier to bottom will be added
- Adding/Removing to all selected through holding ALT will be added

<details>
<summary>Details</summary>

- [ ] Add "Pin to Last" option for modifiers
- [ ]     Draw pin button instead of drag handle in modifier header
- [ ]     Disable drag & drop, operator, and Python reordering of pinned modifiers
- [ ]     Disable reordering of other modifiers past pinned modifiers
- [ ]     Allow multiple pinned modifiers
- [ ] Add "Modifier" option to "Shade Smooth by Angle" operator
- [ ]     Add modifier without duplicating existing modifier
- [ ]     Enable "Pin to Last"
- [ ] Add way to add modifiers to all selected objects
- [ ]     In property editor by holding Alt
- [ ]     In 3D viewport, a new "Modifiers" submenu next to "Constraints"
- [ ]     In outliner, via context menu on object items
- [ ] Improve object instancing ease of use
- [ ]     Add "Object" option next to "Collection" for empty object instancing
</details>

https://projects.blender.org/blender/blender/issues/120230

**Comment by ReinerBforartists** [comment]
Then it could be wise to postpone our changes ...

**Comment by Draise14** [comment]
This was added by Blender, replaced the old one. Now closing. 
<details>
<summary>Details</summary>

SHA-1: 2f289857afa8ebeaa8d81c9e7e12f15af4b6ea3a

    Object: add Shade Auto Smooth operator

Based on the design in #120230.

    Replaces the Shade Smooth by Angle operator with Shade Auto Smooth
    in the object context menu menu.
    The new operator automatically adds and removes the modifier instead
    of being a destructive operation.
    The Shade Smooth and Shade Flat operators now remove the
    Smooth by Angle modifier automatically.
    Add a pin option to modifiers, which limits dragging and keeps the
    modifier after newly added modifiers in the list.

Co-authored-by: Hans Goudey [hans@blender.org](mailto:hans@blender.org)
Pull Request: [projects.blender.org/blender/blender/pulls/121494](https://projects.blender.org/blender/blender/pulls/121494)

</details>

https://github.com/Bforartists/Manual/issues/615
