### ISSUE TITLE
3D View - Add "Adjust Smooth by Angle Modifier" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4189]
https://github.com/Bforartists/Bforartists/assets/35357409/2a8dcd44-a57b-427e-8685-589ad13d23cf

After #4187 is done, now we can adjust the smooth angle of these modifiers on selected objects, similar to previous methods - but from the 3D View. So this would need to be a new operator.

1. Detects if modifier exists
2. If it does, then show the operator
3. When using the operator, pop up a panel
4. Confirm to set angle on selected 

This could be the same operator as the #4187, except that one is replaced by this one if the stack things exists

```
import bpy
import math

class SimpleOperator(bpy.types.Operator):
    bl_idname = "object.simple_operator"
    bl_label = "Modify Smooth by Angle Modifiers"

    angle: bpy.props.FloatProperty(name="Angle", default=30.0)

    @classmethod
    def poll(cls, context):
        return context.active_object is not None

    def execute(self, context):
        # Convert the angle from degrees to radians
        angle_radians = math.radians(self.angle)
        
        # Get all selected objects
        selected_objects = bpy.context.selected_objects

        for obj in selected_objects:
            # Check if the object is a mesh
            if obj.type == 'MESH':
                # Loop through all modifiers of the object
                for modifier in obj.modifiers:
                    # Check if the modifier is a "Nodes" modifier and has the node group "Smooth by Angle"
                    if modifier.type == 'NODES' and modifier.node_group == bpy.data.node_groups["Smooth by Angle"]:
                        # Change the angle
                        modifier["Input_1"] = angle_radians

        # Force a refresh of the Blender interface
        for screen in bpy.data.screens:
            for area in screen.areas:
                area.tag_redraw()
                
        return {'FINISHED'}

    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)

def register():
    bpy.utils.register_class(SimpleOperator)

def unregister():
    bpy.utils.unregister_class(SimpleOperator)

if __name__ == "__main__":
    register()

    # test call
    bpy.ops.object.simple_operator('INVOKE_DEFAULT')

```

## Related tasks:

- [ ] Create operator to change angle of selection from 3D Viewport/Toolbars #4189
- [ ] Expose these operators in the Mesh Properties Editor so old users don't get lost, and can use a similar UX as if in the 3D Viewport, also make it discoverable for older users. #4190
- [x] Create operator to push Smooth by Angle operator to bottom of stack (destructive) from 3D Viewport but as an opt-in UX (not polling always) #4192
- [x]  Create an operator that detects is autosmooth is added to the stack, and removes it. #4191
- [ ] Add "masks" toggles to autosmooth modifier to show the new power.  #4188

**Comment by Draise14** [comment]
Blender is thinking to add this to a degree
- The add Smooth by Angle modifier will be added
- Pinning a modifier to bottom will be added
- Adding/Removing to all selected through holding ALT will be added

<details>
<summary>Details</summary>

- [ ] Add "Pin to Last" option for modifiers
- [ ]     Draw pin button instead of drag handle in modifier header
- [ ]     Disable drag & drop, operator, and Python reordering of pinned modifiers
- [ ]     Disable reordering of other modifiers past pinned modifiers
- [ ]     Allow multiple pinned modifiers
- [ ] Add "Modifier" option to "Shade Smooth by Angle" operator
- [ ]     Add modifier without duplicating existing modifier
- [ ]     Enable "Pin to Last"
- [ ] Add way to add modifiers to all selected objects
- [ ]     In property editor by holding Alt
- [ ]     In 3D viewport, a new "Modifiers" submenu next to "Constraints"
- [ ]     In outliner, via context menu on object items
- [ ] Improve object instancing ease of use
- [ ]     Add "Object" option next to "Collection" for empty object instancing
</details>

https://projects.blender.org/blender/blender/issues/120230

**Comment by ReinerBforartists** [comment]
Then better wait a bit longer.

**Comment by ReinerBforartists** [comment]
I don't think that this task is longer valid. The new system has been refined and is widely accepted. Doing us a change for the sake of change does us no favour.

I will close this task if you don't mind.
