### ISSUE TITLE
Properties Editor - Add Normals operators to a "Normals" panel in the Mesh tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4190]
![bforartists_9aBjEFiXq4](https://github.com/Bforartists/Bforartists/assets/35357409/7f87c254-4099-4435-a6ff-3115cd9db522)

With new operators to manage the modifier stack, and to not hit performance hit with a modifier stack poll constantly ticking, and to be implicit that we are indirectly affecting the modifier stack, we should consistently expose the normal operators to the "normals" panel, so that old users can discover the new way. 

**Existing Operators:**
- Smooth By Angle
- Smooth
- Flat

**New Operators**
- Add Smooth by Angle Modifier #4187

**New Sub-Operators**
- Adjust Smooth By Angle
- Remove Smooth by Angle
- Override Modifier Stack (Push to Bottom)

Relevant Tasks that need to be done first:
#4187

## Related tasks:

- [ ] Create operator to change angle of selection from 3D Viewport/Toolbars #4189
- [ ] Expose these operators in the Mesh Properties Editor so old users don't get lost, and can use a similar UX as if in the 3D Viewport, also make it discoverable for older users. #4190
- [x] Create operator to push Smooth by Angle operator to bottom of stack (destructive) from 3D Viewport but as an opt-in UX (not polling always) #4192
- [x]  Create an operator that detects is autosmooth is added to the stack, and removes it. #4191
- [ ] Add "masks" toggles to autosmooth modifier to show the new power.  #4188

**Comment by Draise14** [comment]
Seems this is an accesibility and discovery to make the modifier stack workflow isolate - but it would be a redundant system... 

Artists may like it... But necessary?
