### ISSUE TITLE
Extensions - Create a smoother "migration" from legacy to pre-downloaded extensions with a single click (no internet needed)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4325]
![bforartists_cfXUP82sZU](https://github.com/Bforartists/Bforartists/assets/35357409/aa43104e-5a53-40c6-bfb1-77a62bd1607b)

Previously Blender had this operator to enable extensions (and thus connect to the internet while at it). I liked it, but it is now removed, and then you have to go to "System" then the "Network" tab to enable internet.. bureaucracy.... The "Enable Repository" button was handy. 

Desired UX: 
1. Go to extensions, see legacy
2. Enable Extensions, see your legacy settings now use Extensions automatically, and you also connect to internet while at it

Maybe we can add this back for the extensions migration (and opt-in to switch legacy to extensions for the user). 

A benefit from adding this is that I could also enable extensions that have been pre-downloaded. I am thinking instead of making the user opt-out of each individual legacy addon to then use the pre-downloaded extension equivalent, I could automate this with a single user opt-in so any activated addon switches to the extension from user migrated settings. 

Question remains if this should be a separate operator, or if we add back the "Use Extensions" user opt-in. Or both.. Two operators ("quick connect + opt-in"  legacy to extensions and "opt-in legacy to extensions")

# Task
- [x] Extensions - Expose the "shortcut" to network settings permanantly in header sub-menu
- [ ] _Extensions - Add/replace operator (optional) to "Use Extensions" to migrate legacy to extensions and connect to internet at the same time, and to enable the pre-downloaded extensions in the library (incase of internet failure)_ Not easily done... blender has a system. 
- [ ] _Extensions - add operator to "Migrate Legacy to Extensions" that can switch user activated legacy addon settings to extensions, and removes the legacy addons from the collection._ Not easily done... blender has a system.

**Comment by Draise14** [comment]
They started to smooth this out, and have an index to "automatically" get the list of the missing addons, we could use something similar to "opt-in" and swap and remove legacy and switch them to extensions when you opt-in to go online.

**Comment by Draise14** [comment]
They made some GUI prompting to help migrate, but you still need an internet connection. 

<details>
<summary>Details</summary>
SHA-1: 2533ff39f9bcdd12d1571f5c8ccda6b671948162

* Extensions: support replacing missing legacy add-ons with extensions

This groups all the add-ons from 4.1 which were enabled but are no
longer distributed with Blender and provides an easy way for users to
install them. This panel is collapsed by default.

Ref !122727

Co-authored-by: Dalai Felinto <dalai@blender.org>

SHA-1: fa5f2354f7ec6d83e87cab0bbd9d80d1d00dfcd8

* Extensions: adjust add-ons shown in missing built-in extensions

Based on feedback in !122727, include previously built-in add-ons
in the built-in extensions panel even if there is no support for
adding it back via the extensions repository.


</details>

**Comment by Draise14** [comment]
New Migration User workflow

Offline? Online? Predownloaded? 

**If Offline**
UX: Use legacy built-in addons as an opt-in and out, accessible from both the Extensions and Addons page. 
1. In the missing Addons it shows the opt-in to legacy addons, or opt-in to Alllow Online Access
2. In the Extensions tab, you can use the notice to opt-into legacy addons, and if you "continue offline" you can still do it from the drop down. 
3. If you opted into legacy addons, you can remove them later (even if you go online).
4. If a user enables/disables the legacy addon, they legacy addons are added/removed automatically. Operators and info in the addon about that. 

**If Online:**
UX: You go the blender way, and have the option to manually reconfigure to the new way, and pre-download extensions in a batch (means we can curate a collection)
1. In the missing addons, you are warned that you can replace with extensions in a more explicit way the Blender way (download one by one)
2. if you opt-online , you can always opt to legacy addons if you want 

**If you were using legacy, and decide to migrate to extensions:**
UX: you can pre-download the built-in extensions equivalents, then manually remove legacy (more hands on power user migration)
1. Download extensions
2. Swap settings manually
2. Remove legacy
